### PR TITLE
GAME-5213 Use the Content-MD5 header for PUT

### PR DESCRIPTION
**Pull request by horvand**
`{error, bad_digest}` is returned if the file was corrupted over the network.
It's assumed that it's worth retrying the request in such a case.

Note that using the `Content-MD5` header also means changes to the signature in `Authorization:`

### CODE REVIEW

**Review by maxkuzmins — COMMENTED** [review]
@horvand do you see an easy way of testing it? Would be nice to have at least one test for a happy path.

**Comment by horvand** [comment]
Eunit tests in the repository actually work.
For the negative tests I changed the code to send a wrong MD5 checksum with the requests.

**Comment by horvand** [comment]
```diff
diff --git a/src/s3_lib.erl b/src/s3_lib.erl
index 553e6da..5eebf2c 100644
--- a/src/s3_lib.erl
+++ b/src/s3_lib.erl
@@ -123,7 +123,8 @@ build_full_url(undefined, Bucket, Path) ->
 build_full_url(Endpoint, Bucket, Path) ->
     lists:flatten(["http://", build_host(Endpoint, Bucket), "/", Path]).

-request(Config, Method, Bucket, Path, Headers, Body) ->
+request(Config, Method, Bucket, Path, Headers0, Body) ->
+    Headers = lists:keyreplace("Content-MD5", 1, Headers0, {"Content-MD5", md5_hash_string(<<>>)}),
     Date = httpd_util:rfc1123_date(),
     Url = build_url(Config#config.endpoint, Bucket, Path),
     ContentMD5 = case lists:keyfind("Content-MD5", 1, Headers) of
```

**Review by maxkuzmins — APPROVED** [review]
It's outside of the scope of this ticket, but it would be really nice to have a .travis.yml for this repo.

**Review by sata — APPROVED** [review]

**Pull request merged**
